version: '3'

services:

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - elastic_network

  kibana:
    container_name: 'kibana_ui'
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
      - 9300:9300
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - elastic_network
    
networks:
  elastic_network:
    driver: bridge
